# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aiac < Formula
  desc "Artificial Intelligence Infrastructure-as-Code Generator"
  homepage "https://github.com/gofireflyio/aiac"
  version "5.0.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/gofireflyio/aiac/releases/download/v5.0.0/aiac_5.0.0_darwin-amd64.tar.gz"
      sha256 "7f54caeafbff0bb3f38490929909ebbe1bdc9bd005cbe8c9331dcaffc49f2630"

      def install
        bin.install "aiac"
      end
    end
    on_arm do
      url "https://github.com/gofireflyio/aiac/releases/download/v5.0.0/aiac_5.0.0_darwin-arm64.tar.gz"
      sha256 "3f432682808fbce65ada766dc62bf57bcdee2eb80409b1b657c039cfd4cbb0b1"

      def install
        bin.install "aiac"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gofireflyio/aiac/releases/download/v5.0.0/aiac_5.0.0_linux-amd64.tar.gz"
        sha256 "c63d0c9978b314eb34ece0ed3202ee5d49e3b87aa994b0cf0b40dcc0492a12a3"

        def install
          bin.install "aiac"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gofireflyio/aiac/releases/download/v5.0.0/aiac_5.0.0_linux-arm64.tar.gz"
        sha256 "2b9d2c1a43c66b649dd7650ee7d97bde6feafab1c1f8eea4009769c501f91afe"

        def install
          bin.install "aiac"
        end
      end
    end
  end

  test do
    system "#{bin}/aiac", "--help"
  end
end
