# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aiac < Formula
  desc "Artificial Intelligence Infrastructure-as-Code Generator"
  homepage "https://github.com/gofireflyio/aiac"
  version "4.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gofireflyio/aiac/releases/download/v4.2.0/aiac_4.2.0_macOS-64bit.tar.gz"
      sha256 "b8f646ea3f040c7b7ead7e484a0085431e699bea6809d6faf17337333148afb8"

      def install
        bin.install "aiac"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gofireflyio/aiac/releases/download/v4.2.0/aiac_4.2.0_macOS-ARM64.tar.gz"
      sha256 "333d6e23fcb00d4f2603fc65abc65e9e43e91979158b6c8eef49322b788d7892"

      def install
        bin.install "aiac"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gofireflyio/aiac/releases/download/v4.2.0/aiac_4.2.0_Linux-ARM64.tar.gz"
      sha256 "bb9c7408bac1017378accffb024fbe64ffceb0f16255e703762ae7dadaf3f9cb"

      def install
        bin.install "aiac"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gofireflyio/aiac/releases/download/v4.2.0/aiac_4.2.0_Linux-64bit.tar.gz"
      sha256 "6cdb8eedb8ba22d2449dc6b3af43f5279a6bbca6b038ece3e520243b58f15a51"

      def install
        bin.install "aiac"
      end
    end
  end

  test do
    system "#{bin}/aiac", "--help"
  end
end
